/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pkg1;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;


/**
 *
 * @author Amil De Silva
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    public addStudent() {
        initComponents();
        
        try{
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";
            
            int id = 1;
            String str1 = String.valueOf(id);
            jidlabel.setText(str1);
            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select max(sid) from Student");
            
            while(rs.next()){
                
                id = rs.getInt(1);
                id = id+1;
                String str = String.valueOf(id);
                jidlabel.setText(str);
            }
                    
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jidlabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextFieldMadress = new javax.swing.JTextField();
        jTextFieldMmobile = new javax.swing.JTextField();
        jTextFieldMname = new javax.swing.JTextField();
        jTextFieldFatherAddress = new javax.swing.JTextField();
        jTextFieldFatherMobile = new javax.swing.JTextField();
        jComboBoxgrade = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jidlabel.setFont(new java.awt.Font("Souvenir Lt BT", 1, 24)); // NOI18N
        jidlabel.setText("00");
        getContentPane().add(jidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, 50));

        jTextField1.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 250, -1));

        jTextField2.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, -1));

        jTextField3.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 250, -1));

        jTextField4.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 250, -1));

        jTextField6.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 250, -1));

        jTextFieldMadress.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldMadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 250, -1));

        jTextFieldMmobile.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldMmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 250, -1));

        jTextFieldMname.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 250, -1));

        jTextFieldFatherAddress.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldFatherAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 250, -1));

        jTextFieldFatherMobile.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextFieldFatherMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 250, -1));

        jComboBoxgrade.setFont(new java.awt.Font("Souvenir Lt BT", 1, 18)); // NOI18N
        jComboBoxgrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade 01", "Grade 02", "Grade 03", "Grade 04", "Grade 05", "Grade 06", "Grade 07", "Grade 08", "Grade 09", "Grade 10", "Grade 11" }));
        getContentPane().add(jComboBoxgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        jTextField14.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 250, -1));

        jTextField13.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 250, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 160, 60));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 160, 60));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/back logo.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 580, 60, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/addstudent.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        setVisible(false);
        new addStudent().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = jidlabel.getText();
        String fullname = jTextField2.getText();
        String age = jTextField3.getText();
        String address = jTextField6.getText();
        String mobile = jTextField1.getText();
        String email = jTextField13.getText();
        String dob = jTextField4.getText();
        String grade = (String)jComboBoxgrade.getSelectedItem();
        String enrollmentDate = jTextArea1.getText();
        String Fname = jTextField14.getText();
        String Fmobile = jTextFieldFatherMobile.getText();
        String FAddress = jTextFieldFatherAddress.getText();
        String Mname = jTextFieldMname.getText();
        String Mmobile = jTextFieldMmobile.getText();
        String Maddress = jTextFieldMadress.getText();
        
        
        
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";

        
        
        try{
            
            
            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            PreparedStatement ps = conn.prepareStatement("insert into Student values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            ps.setString(1, id);
            ps.setString(2, fullname);
            ps.setString(3, age);
            ps.setString(4, address);
            ps.setString(5, mobile);
            ps.setString(6, email);
            ps.setString(7, dob);
            ps.setString(8, grade);
            ps.setString(9, enrollmentDate);
            ps.setString(10, Fname);
            ps.setString(11, Fmobile);
            ps.setString(12, FAddress);
            ps.setString(13, Mname);
            ps.setString(14, Mmobile);
            ps.setString(15, Maddress);
     
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully Saved");
            setVisible(false);
            new addStudent().setVisible(true);

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomeFrame f1=new HomeFrame();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxgrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldFatherAddress;
    private javax.swing.JTextField jTextFieldFatherMobile;
    private javax.swing.JTextField jTextFieldMadress;
    private javax.swing.JTextField jTextFieldMmobile;
    private javax.swing.JTextField jTextFieldMname;
    private javax.swing.JLabel jidlabel;
    // End of variables declaration//GEN-END:variables
}
