/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pkg1;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JOptionPane;


/**
 *
 * @author Amil De Silva
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jwebsite = new javax.swing.JToggleButton();
        jlogout = new javax.swing.JToggleButton();
        jlogout1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jwebsite.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jwebsite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/internet logo.png"))); // NOI18N
        jwebsite.setText("Visit Our Website");
        jwebsite.setBorder(null);
        jwebsite.setBorderPainted(false);
        jwebsite.setContentAreaFilled(false);
        jwebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwebsiteActionPerformed(evt);
            }
        });
        getContentPane().add(jwebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 630, 270, 40));

        jlogout.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/logbutton.png"))); // NOI18N
        jlogout.setText("Log Out");
        jlogout.setBorder(null);
        jlogout.setBorderPainted(false);
        jlogout.setContentAreaFilled(false);
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 190, 70));

        jlogout1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jlogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/tasklogo.png"))); // NOI18N
        jlogout1.setText("Perform Tasks");
        jlogout1.setBorder(null);
        jlogout1.setBorderPainted(false);
        jlogout1.setContentAreaFilled(false);
        jlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogout1ActionPerformed(evt);
            }
        });
        getContentPane().add(jlogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/mainframe.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jwebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwebsiteActionPerformed
       
       try
       {
        Desktop.getDesktop().browse(new URL("https://www.asiangrammar.lk/").toURI());
       }
       catch(IOException | URISyntaxException e)
       {
           JOptionPane.showMessageDialog(null,"Invalid Error Occured");
       }
    }//GEN-LAST:event_jwebsiteActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
       LoginFrame f1=new LoginFrame();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogout1ActionPerformed
       
        HomeFrame h1=new HomeFrame();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jlogout;
    private javax.swing.JToggleButton jlogout1;
    private javax.swing.JToggleButton jwebsite;
    // End of variables declaration//GEN-END:variables
}
