/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pkg1;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amil De Silva
 */
public class payment extends javax.swing.JFrame {

    public void tableinfo(){
        
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        String id = jtxtID.getText();
        
        
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";
        
        try{
            
            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from Payment where sid='"+id+"'");           
            while(rs.next()){
                
                dtm.addRow(new Object[]{rs.getString(2),rs.getString(1),rs.getString(4), rs.getString(5), rs.getString(6)});
            }            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
        }       
    }
    
    public void date(){
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd - MMM - yyyy");
        Date date = new Date();
        String month = sdf.format(date);
        jLabel2.setText(month);        
        
    }
    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
        date();
        
          try{
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";
            
            int id = 1;
            String str1 = String.valueOf(id);
            jLabelpID.setText(str1);
            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select max(sid) from Payment");
            
            while(rs.next()){
                
                id = rs.getInt(1);
                id = id+1;
                String str = String.valueOf(id);
                jLabelpID.setText(str);
            }
                    
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itxtName = new javax.swing.JTextField();
        jtxtFees = new javax.swing.JTextField();
        jtxtAdditionalFees = new javax.swing.JTextField();
        jtxtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtemail = new javax.swing.JTextField();
        jtxtmobile = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelpID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itxtName.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        itxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itxtNameActionPerformed(evt);
            }
        });
        getContentPane().add(itxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 160, 30));

        jtxtFees.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        jtxtFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFeesActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 160, 30));

        jtxtAdditionalFees.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        jtxtAdditionalFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdditionalFeesActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtAdditionalFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 140, 30));

        jtxtID.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        jtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 140, 40));

        jLabel2.setFont(new java.awt.Font("Serifa BT", 0, 18)); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/seacrhbutton.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 60, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Student ID", "Name ", "Term Fees", "Additional Fees"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 500, -1));

        jtxtemail.setFont(new java.awt.Font("Souvenir Lt BT", 1, 14)); // NOI18N
        jtxtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemailActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 180, 30));

        jtxtmobile.setFont(new java.awt.Font("Souvenir Lt BT", 1, 20)); // NOI18N
        jtxtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 160, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 160, 60));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 160, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/back logo.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 480, 60, 60));

        jLabelpID.setFont(new java.awt.Font("Serifa BT", 0, 22)); // NOI18N
        getContentPane().add(jLabelpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw/pkg1/payment.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itxtNameActionPerformed

    private void jtxtFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFeesActionPerformed

    private void jtxtAdditionalFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdditionalFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdditionalFeesActionPerformed

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Search Button
        tableinfo();
        int checkid = 0;
        String id = jtxtID.getText();
        
        
        
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";

        try{

            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from student where sid='"+id+"'");

            while(rs.next()){

                checkid = 1;
                jtxtID.setEditable(false);
                itxtName.setText(rs.getString(2));
               jtxtmobile.setText(rs.getString(5));
                jtxtemail.setText(rs.getString(6));
                
            }

            if(checkid == 0){

                JOptionPane.showMessageDialog(null, "Member ID does not Exist!");

            }

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemailActionPerformed

    private void jtxtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmobileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        String id = jtxtID.getText();
         String pid = jLabelpID.getText();
        String month = jLabel2.getText();
        String name = itxtName.getText();
        double termfees = Double.parseDouble(jtxtFees.getText());
        double additionalfees = Double.parseDouble(jtxtAdditionalFees.getText());
        
            String SUrl = "jdbc:MySQL://localhost:3306/AGS";
            String SUser = "root";
            String SPass = "sithil@12345";

        try{

            Connection conn = DriverManager.getConnection(SUrl,SUser,SPass);
            PreparedStatement ps = conn.prepareStatement("insert into Payment values(?,?,?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, pid);
            ps.setString(3, month);
            ps.setString(4, name);
            ps.setDouble(5, termfees);
            ps.setDouble(6, additionalfees);
            ps.executeUpdate();
            tableinfo();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new payment().setVisible(true);
            

        }catch(HeadlessException | SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        this.setVisible(false);
        payment p1 =new payment();
        p1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HomeFrame f1=new HomeFrame();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itxtName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelpID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtAdditionalFees;
    private javax.swing.JTextField jtxtFees;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtmobile;
    // End of variables declaration//GEN-END:variables
}
